USE [master]
GO

/****** Object:  Database [quiz]    Script Date: 07/01/2025 3:46:15 pm ******/
CREATE DATABASE [quiz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'quiz', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\quiz.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'quiz_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\quiz_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [quiz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [quiz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [quiz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [quiz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [quiz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [quiz] SET ARITHABORT OFF 
GO

ALTER DATABASE [quiz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [quiz] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [quiz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [quiz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [quiz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [quiz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [quiz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [quiz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [quiz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [quiz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [quiz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [quiz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [quiz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [quiz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [quiz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [quiz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [quiz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [quiz] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [quiz] SET  MULTI_USER 
GO

ALTER DATABASE [quiz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [quiz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [quiz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [quiz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [quiz] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [quiz] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [quiz] SET QUERY_STORE = ON
GO

ALTER DATABASE [quiz] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [quiz] SET  READ_WRITE 
GO

